# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddItemtoComplexMaterial.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddItemToComplexMaterial(object):
    def setupUi(self, AddItemToComplexMaterial):
        AddItemToComplexMaterial.setObjectName("AddItemToComplexMaterial")
        AddItemToComplexMaterial.resize(1082, 480)
        self.gridLayout = QtWidgets.QGridLayout(AddItemToComplexMaterial)
        self.gridLayout.setObjectName("gridLayout")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(AddItemToComplexMaterial)
        self.doubleSpinBox_2.setDecimals(4)
        self.doubleSpinBox_2.setMaximum(99999.99)
        self.doubleSpinBox_2.setProperty("value", 1.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout.addWidget(self.doubleSpinBox_2, 3, 1, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(AddItemToComplexMaterial)
        self.textEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 1, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(AddItemToComplexMaterial)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(AddItemToComplexMaterial)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(AddItemToComplexMaterial)
        self.doubleSpinBox.setDecimals(4)
        self.doubleSpinBox.setMaximum(99999.99)
        self.doubleSpinBox.setProperty("value", 1.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 3, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(AddItemToComplexMaterial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 2)
        self.label = QtWidgets.QLabel(AddItemToComplexMaterial)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)

        self.retranslateUi(AddItemToComplexMaterial)
        QtCore.QMetaObject.connectSlotsByName(AddItemToComplexMaterial)

    def retranslateUi(self, AddItemToComplexMaterial):
        _translate = QtCore.QCoreApplication.translate
        AddItemToComplexMaterial.setWindowTitle(_translate("AddItemToComplexMaterial", "Добавить позицию в комплексный материал"))
        self.pushButton.setText(_translate("AddItemToComplexMaterial", "Добавить"))
        self.label_2.setText(_translate("AddItemToComplexMaterial", "Затрачено едениц"))
        self.label.setText(_translate("AddItemToComplexMaterial", "Количество едениц в упаковке"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddItemToComplexMaterial = QtWidgets.QDialog()
    ui = Ui_AddItemToComplexMaterial()
    ui.setupUi(AddItemToComplexMaterial)
    AddItemToComplexMaterial.show()
    sys.exit(app.exec_())
