# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddPositionToPatient.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddPositionToPatient(object):
    def setupUi(self, AddPositionToPatient):
        AddPositionToPatient.setObjectName("AddPositionToPatient")
        AddPositionToPatient.resize(1082, 480)
        self.gridLayout = QtWidgets.QGridLayout(AddPositionToPatient)
        self.gridLayout.setObjectName("gridLayout")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(AddPositionToPatient)
        self.doubleSpinBox.setDecimals(4)
        self.doubleSpinBox.setMaximum(99999.99)
        self.doubleSpinBox.setProperty("value", 1.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 4, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(AddPositionToPatient)
        self.textEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 2, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(AddPositionToPatient)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 5, 0, 1, 2)
        self.lineEdit = QtWidgets.QLineEdit(AddPositionToPatient)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 2)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(AddPositionToPatient)
        self.doubleSpinBox_2.setDecimals(4)
        self.doubleSpinBox_2.setMaximum(99999.99)
        self.doubleSpinBox_2.setProperty("value", 1.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout.addWidget(self.doubleSpinBox_2, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(AddPositionToPatient)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(AddPositionToPatient)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(AddPositionToPatient)
        self.comboBox.setEnabled(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 1)

        self.retranslateUi(AddPositionToPatient)
        QtCore.QMetaObject.connectSlotsByName(AddPositionToPatient)

    def retranslateUi(self, AddPositionToPatient):
        _translate = QtCore.QCoreApplication.translate
        AddPositionToPatient.setWindowTitle(_translate("AddPositionToPatient", "Добавить позицию расхода на пациента"))
        self.pushButton.setText(_translate("AddPositionToPatient", "Добавить"))
        self.label.setText(_translate("AddPositionToPatient", "Количество едениц в упаковке"))
        self.label_2.setText(_translate("AddPositionToPatient", "Затрачено едениц"))
        self.comboBox.setItemText(0, _translate("AddPositionToPatient", "Расходные материалы"))
        self.comboBox.setItemText(1, _translate("AddPositionToPatient", "Лекарственные препараты"))
        self.comboBox.setItemText(2, _translate("AddPositionToPatient", "Дезинфицирующие средства"))
        self.comboBox.setItemText(3, _translate("AddPositionToPatient", "Иное"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddPositionToPatient = QtWidgets.QDialog()
    ui = Ui_AddPositionToPatient()
    ui.setupUi(AddPositionToPatient)
    AddPositionToPatient.show()
    sys.exit(app.exec_())
