# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewPatient.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewPatient(object):
    def setupUi(self, NewPatient):
        NewPatient.setObjectName("NewPatient")
        NewPatient.resize(741, 295)
        self.gridLayout = QtWidgets.QGridLayout(NewPatient)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(NewPatient)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(NewPatient)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 2)
        self.lineEdit_2 = QtWidgets.QLineEdit(NewPatient)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 3, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(NewPatient)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(NewPatient)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 8, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(NewPatient)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 5, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(NewPatient)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 0, 1, 1)
        self.dateEdit_2 = QtWidgets.QDateEdit(NewPatient)
        self.dateEdit_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.gridLayout.addWidget(self.dateEdit_2, 9, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(NewPatient)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 0, 1, 2)
        self.dateEdit = QtWidgets.QDateEdit(NewPatient)
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setCurrentSectionIndex(0)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 9, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(NewPatient)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 10, 1, 1, 1)

        self.retranslateUi(NewPatient)
        QtCore.QMetaObject.connectSlotsByName(NewPatient)

    def retranslateUi(self, NewPatient):
        _translate = QtCore.QCoreApplication.translate
        NewPatient.setWindowTitle(_translate("NewPatient", "Новый пациент"))
        self.label.setText(_translate("NewPatient", "ФИО пациента"))
        self.label_2.setText(_translate("NewPatient", "№ истории болезни"))
        self.label_3.setText(_translate("NewPatient", "Статус"))
        self.label_4.setText(_translate("NewPatient", "Выписан"))
        self.comboBox.setItemText(0, _translate("NewPatient", "Раненый"))
        self.comboBox.setItemText(1, _translate("NewPatient", "Больной"))
        self.label_5.setText(_translate("NewPatient", "Поступил"))
        self.dateEdit_2.setDisplayFormat(_translate("NewPatient", "yyyy-MM-dd"))
        self.dateEdit.setDisplayFormat(_translate("NewPatient", "yyyy-MM-dd"))
        self.pushButton.setText(_translate("NewPatient", "Готово"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewPatient = QtWidgets.QDialog()
    ui = Ui_NewPatient()
    ui.setupUi(NewPatient)
    NewPatient.show()
    sys.exit(app.exec_())
