# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PatientAll_costs.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PatientAllCosts(object):
    def setupUi(self, PatientAllCosts):
        PatientAllCosts.setObjectName("PatientAllCosts")
        PatientAllCosts.resize(1105, 624)
        font = QtGui.QFont()
        font.setFamily("Onyx")
        PatientAllCosts.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(PatientAllCosts)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(PatientAllCosts)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(280)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(54)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableWidget, 2, 0, 1, 5)
        self.pushButton = QtWidgets.QPushButton(PatientAllCosts)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(PatientAllCosts)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 4, 2, 1)
        self.label = QtWidgets.QLabel(PatientAllCosts)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setMidLineWidth(5)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 2, 3)
        self.pushButton_2 = QtWidgets.QPushButton(PatientAllCosts)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 3, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(PatientAllCosts)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(13)
        font.setItalic(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(PatientAllCosts)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(PatientAllCosts)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 3, 1, 1)

        self.retranslateUi(PatientAllCosts)
        QtCore.QMetaObject.connectSlotsByName(PatientAllCosts)

    def retranslateUi(self, PatientAllCosts):
        _translate = QtCore.QCoreApplication.translate
        PatientAllCosts.setWindowTitle(_translate("PatientAllCosts", "Расходы на пациента"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("PatientAllCosts", "Наименование"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("PatientAllCosts", "Ед. измерения"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("PatientAllCosts", "Количество"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("PatientAllCosts", "Сумма за позицию"))
        self.pushButton.setText(_translate("PatientAllCosts", "Добавить позицию"))
        self.label_2.setText(_translate("PatientAllCosts", "История"))
        self.label.setText(_translate("PatientAllCosts", "ФИО"))
        self.pushButton_2.setText(_translate("PatientAllCosts", "Удалить позицию"))
        self.label_4.setText(_translate("PatientAllCosts", "0"))
        self.label_3.setText(_translate("PatientAllCosts", "Итого на пациента"))
        self.label_5.setText(_translate("PatientAllCosts", "История"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PatientAllCosts = QtWidgets.QDialog()
    ui = Ui_PatientAllCosts()
    ui.setupUi(PatientAllCosts)
    PatientAllCosts.show()
    sys.exit(app.exec_())
