# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WaitingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WaitingWidget(object):
    def setupUi(self, WaitingWidget):
        WaitingWidget.setObjectName("WaitingWidget")
        WaitingWidget.setEnabled(True)
        WaitingWidget.resize(347, 257)
        self.label = QtWidgets.QLabel(WaitingWidget)
        self.label.setGeometry(QtCore.QRect(10, 30, 331, 151))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")

        self.retranslateUi(WaitingWidget)
        QtCore.QMetaObject.connectSlotsByName(WaitingWidget)

    def retranslateUi(self, WaitingWidget):
        _translate = QtCore.QCoreApplication.translate
        WaitingWidget.setWindowTitle(_translate("WaitingWidget", "Подождите"))
        self.label.setText(_translate("WaitingWidget", "Подождите, идёт импорт"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WaitingWidget = QtWidgets.QWidget()
    ui = Ui_WaitingWidget()
    ui.setupUi(WaitingWidget)
    WaitingWidget.show()
    sys.exit(app.exec_())
